Setup GET Routes for Filtering Donation Tables
ctc-uci/fph-backend pull request #22
Opened 2024-02-15 06:30 UTC by Xire7

API Get Routes For FPH-Frontend's Donation Table Tracker time filters

2024-02-15 06:31 UTC, ctc-devops commented on routes/donationRouter.js
> +    console.error(error);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/latest/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2024-02-15 06:31 UTC, ctc-devops commented on routes/donationRouter.js
> +    console.error(error);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/latest/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2024-02-15 06:31 UTC, ctc-devops commented on routes/donationRouter.js
> +    console.error(error);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/latest/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2024-02-15 06:31 UTC, ctc-devops commented on routes/donationRouter.js
> +    console.error(error);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/latest/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2024-02-17 17:55 UTC, srukelman requested changes
good work jits

2024-02-17 17:55 UTC, srukelman commented on routes/donationRouter.js
> +    console.error(error);
remove unnecessary console statement

2024-02-17 17:55 UTC, srukelman commented on routes/donationRouter.js
> +    console.error(error);
remove unnecessary console statement

2024-02-17 17:55 UTC, srukelman commented on routes/donationRouter.js
> +    console.error(error);
remove unnecessary console statement

2024-02-17 17:55 UTC, srukelman commented on routes/donationRouter.js
> +    console.error(error);
remove unnecessary console statement

2024-02-17 17:55 UTC, srukelman commented on routes/donationRouter.js
> +    res.status(500).send({ message: 'Internal Server Error' });
send error.message instead of 'Internal Server Error'

2024-02-17 17:55 UTC, srukelman commented on routes/donationRouter.js
> +    res.status(500).send({ message: 'Internal Server Error' });
send error.message instead of 'Internal Server Error'

2024-02-17 17:55 UTC, srukelman commented on routes/donationRouter.js
> +    res.status(500).send({ message: 'Internal Server Error' });
send error.message instead of 'Internal Server Error'

2024-02-17 17:55 UTC, srukelman commented on routes/donationRouter.js
> +    res.status(500).send({ message: 'Internal Server Error' });
send error.message instead of 'Internal Server Error'

2024-02-17 17:55 UTC, srukelman commented on routes/donationRouter.js
make a single route with the filter passed as a parameter, then use that parameter's value to set the query

2024-02-20 00:11 UTC, merged